export const schoolSubjects = [
  "General",
  "Lengua",
  "Lectoescritura",
  "Comprension lectora",
  "Produccion escrita",
  "Conciencia fonologica",
  "Lenguaje",
  "Comunicacion",
  "Matematica",
  "Resolucion de problemas",
  "Ciencias Naturales",
  "Ciencias Sociales",
  "Ingles",
  "Musica",
  "Arte",
  "Plastica",
  "Tecnologia",
  "Educacion Fisica",
  "Habitos de estudio",
  "Organizacion",
  "Atencion",
  "Memoria",
  "Funciones ejecutivas",
  "Integracion escolar",
  "Gestion",
] as const;
